spring:
  application:
    name: Medals-Backend
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres_db:5432/medals
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
cors:
  allowedOrigins:
    - http://localhost:5173
    - http://192.168.178.21:5173
    - http://localhost:3000
    - https://stratssync.com
    - https://localhost:1024
app:
  admin:
    enabled: true
    admins:
        - email: ${ADMIN_EMAIL}
          first-name: ${ADMIN_FIRST_NAME}
          last-name: ${ADMIN_LAST_NAME}
  security:
    identity-token-expiration-time: 3600000 # 1 hour
    refresh-token-expiration-time: 2678400000 # 1 month
    secret-key: ${JWS_SECRET}
  email:
    url: ${EMAIL_ENDPOINT} # supply with email api endpoint
    author: ${EMAIL_AUTHOR}
    templates:
      set-password-notification: "template_account_created"
      invite-trainer-notification: "template_trainer_invitation"
      reset-password-notification: "template_reset_password"
      password-reset-notification: "template_password_reset"
  otc:
    set-password-token-validity-duration: 604800000 # 1 week
    reset-password-token-validity-duration: 3600000 # 1 hour
