spring:
  application:
    name: Medals-Backend
  profiles:
    default: local
cors:
  allowedOrigins:
    - http://localhost:5173
    - http://192.168.178.21:5173
    - http://localhost:3000
app:
  dummies:
    enabled: true
  admin:
    enabled: true
    admins:
      - email: "admin@example.org"
        first-name: "Mighty"
        last-name: "God"
  security:
    identity-token-expiration-time: 3600000 # 1 hour
    refresh-token-expiration-time: 2678400000 # 1 month
    secret-key: 2bdff806c775df3d3a9a720924294d3f6dfa4e4e8f65183294bc8b8f043987ac # jwt secret key (REPLACE IN PRODUCTION!!)
  email:
    url: "https://google.com" # supply with email api endpoint
    author: "noreply@medals.com"
    templates:
      set-password-notification: "template_account_created.html"
      invite-trainer: "template_trainer_invitation.html"
  otc:
    set-password-token-validity-duration: 604800000 # 1 week
