spring:
  application:
    name: Medals-Backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  profiles:
    default: dev
