spring:
  application:
    name: Medals-Backend
  profiles:
    default: local
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
cors:
  allowedOrigins:
    - http://localhost:5173
    - http://192.168.178.21:5173
    - http://localhost:3000
    - https://stratssync.com
app:
  dummies:
    enabled: true
  mailClient:
    url: https://jannekeipert.de/mail-service
    auth-key: ${MAIL_AUTH_KEY:}
  admin:
    enabled: true
    admins:
      - email: "admin@example.com"
        first-name: "Mighty"
        last-name: "God"
  security:
    identity-token-expiration-time: 3600000 # 1 hour
    refresh-token-expiration-time: 2678400000 # 1 month
    athlete-request-token-expiration-time: 2678400000 # 1 month
    secret-key: 2bdff806c775df3d3a9a720924294d3f6dfa4e4e8f65183294bc8b8f043987ac # jwt secret key (REPLACE IN PRODUCTION!!)
  email:
    templates:
      set-password-notification: "template_account_created"
      invite-trainer-notification: "template_trainer_invitation"
      reset-password-notification: "template_reset_password"
      reset-password-confirmation-notification: "template_reset_password_confirmation"
      trainer-request-athlete-access-notification: "template_trainer_request_athlete_access"
      role-added-notification: "template_role_added"
  notification:
    front-end-base-url: "http://localhost:5173"
  otc:
    set-password-token-validity-duration: 604800000 # 1 week
    reset-password-token-validity-duration: 3600000 # 1 hour
  files:
    disciplines-csv: "discipline_ratings/disciplines.csv"
    rating-metrics-csv: "discipline_ratings/discipline_rating_metric.csv"
