package com.medals.medalsbackend;

import com.medals.medalsbackend.entity.Athlete;
import com.medals.medalsbackend.entity.medal.MedalCollection;
import com.medals.medalsbackend.entity.medal.MedalType;

import java.time.LocalDate;
import java.util.List;

public class DummyData {

    public static final List<Athlete> ATHLETES = List.of(
            Athlete.builder().firstName("John").lastName("Doe").birthdate(LocalDate.of(2003, 3, 7)).email("john@doe.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Jane").lastName("Smith").birthdate(LocalDate.of(2004, 4, 10)).email("jane.smith@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Emily").lastName("Johnson").birthdate(LocalDate.of(2005, 5, 13)).email("emily.johnson@example.org").gender('d').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Michael").lastName("Brown").birthdate(LocalDate.of(2000, 7, 19)).email("michael.brown@example.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Sarah").lastName("Davis").birthdate(LocalDate.of(2002, 2, 14)).email("sarah.davis@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Chris").lastName("Taylor").birthdate(LocalDate.of(2003, 11, 3)).email("chris.taylor@example.org").gender('m').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Jessica").lastName("Wilson").birthdate(LocalDate.of(1999, 6, 24)).email("jessica.wilson@example.org").gender('f').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("David").lastName("White").birthdate(LocalDate.of(2001, 9, 18)).email("david.white@example.org").gender('m').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Ashley").lastName("Martin").birthdate(LocalDate.of(2000, 12, 25)).email("ashley.martin@example.org").gender('f').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("James").lastName("Garcia").birthdate(LocalDate.of(1998, 8, 8)).email("james.garcia@example.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Olivia").lastName("Martinez").birthdate(LocalDate.of(2004, 1, 31)).email("olivia.martinez@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Daniel").lastName("Hernandez").birthdate(LocalDate.of(2005, 5, 5)).email("daniel.hernandez@example.org").gender('m').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Sophia").lastName("Lopez").birthdate(LocalDate.of(2002, 3, 17)).email("sophia.lopez@example.org").gender('f').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Ethan").lastName("Gonzalez").birthdate(LocalDate.of(1999, 4, 29)).email("ethan.gonzalez@example.org").gender('m').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Isabella").lastName("Rodriguez").birthdate(LocalDate.of(2001, 10, 12)).email("isabella.rodriguez@example.org").gender('f').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Alexander").lastName("Perez").birthdate(LocalDate.of(2003, 6, 2)).email("alexander.perez@example.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Mia").lastName("Thomas").birthdate(LocalDate.of(2000, 9, 15)).email("mia.thomas@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Benjamin").lastName("Walker").birthdate(LocalDate.of(1998, 12, 1)).email("benjamin.walker@example.org").gender('m').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Charlotte").lastName("Hall").birthdate(LocalDate.of(2004, 11, 20)).email("charlotte.hall@example.org").gender('f').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Jacob").lastName("Young").birthdate(LocalDate.of(2001, 8, 6)).email("jacob.young@example.org").gender('m').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Liam").lastName("Morgan").birthdate(LocalDate.of(2002, 5, 22)).email("liam.morgan@example.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Emma").lastName("Harris").birthdate(LocalDate.of(1999, 11, 11)).email("emma.harris@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Noah").lastName("Clark").birthdate(LocalDate.of(2001, 3, 15)).email("noah.clark@example.org").gender('m').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Ava").lastName("Lee").birthdate(LocalDate.of(2000, 6, 5)).email("ava.lee@example.org").gender('f').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Lucas").lastName("Scott").birthdate(LocalDate.of(2003, 4, 27)).email("lucas.scott@example.org").gender('m').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("Sophia").lastName("Adams").birthdate(LocalDate.of(1998, 9, 30)).email("sophia.adams@example.org").gender('f').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("William").lastName("Robinson").birthdate(LocalDate.of(2004, 12, 19)).email("william.robinson@example.org").gender('m').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.SILVER).build()).build(),
            Athlete.builder().firstName("Isabella").lastName("Walker").birthdate(LocalDate.of(2001, 2, 10)).email("isabella.walker@example.org").gender('f').totalMedal(MedalType.GOLD).medalCollection(MedalCollection.builder().medalEndurance(MedalType.BRONZE).medalCoordination(MedalType.SILVER).medalStrength(MedalType.GOLD).medalSpeed(MedalType.BRONZE).build()).build(),
            Athlete.builder().firstName("James").lastName("Young").birthdate(LocalDate.of(1997, 7, 8)).email("james.young@example.org").gender('m').totalMedal(MedalType.SILVER).medalCollection(MedalCollection.builder().medalEndurance(MedalType.GOLD).medalCoordination(MedalType.BRONZE).medalStrength(MedalType.SILVER).medalSpeed(MedalType.GOLD).build()).build(),
            Athlete.builder().firstName("Mia").lastName("Hall").birthdate(LocalDate.of(1996, 8, 3)).email("mia.hall@example.org").gender('f').totalMedal(MedalType.BRONZE).medalCollection(MedalCollection.builder().medalEndurance(MedalType.SILVER).medalCoordination(MedalType.GOLD).medalStrength(MedalType.BRONZE).medalSpeed(MedalType.SILVER).build()).build()

    );
}
