name: Build and Test Backend

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Step up JDK
        uses: actions/setup-java@v2
        with:
          distribution: jetbrains
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Step up JDK
        uses: actions/setup-java@v2
        with:
          distribution: jetbrains
          java-version: "21"
          cache: "maven"

      - name: Test the application
        run: mvn test
