name: Build Backend

on:
  push:
    branches:
      - main

jobs:
  buid-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Step up JDK
        uses: actions/setup-java@v2
        with:
          distribution: jetbrains
          java-version: "21"
          cache: "maven"

      - name: Install Packages
        run: mvn clean install

      - name: Build with Spring Boot
        run: mvn spring-boot:run -DskipTests

      - name: Test the application
        run: mvn test
