name: Build and Test Backend

on: push

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup


  publish-build:
    name: Publish Backend
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.MEDALS_DOCKER_USERNAME }}
          password: ${{ secrets.MEDALS_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{vars.MEDALS_DOCKER_USERNAME}}/medals-backend

      - name: Push Docker image
        run: docker push ${{vars.MEDALS_DOCKER_USERNAME}}/medals-backend

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MEDALS_DEPLOYMENT_HOST }}
          username: ${{ secrets.MEDALS_DEPLOYMENT_USERNAME }}
          key: ${{ secrets.MEDALS_DEPLOYMENT_SSH_TOKEN }}
          port: ${{ secrets.MEDALS_DEPLOYMENT_PORT }}
          script: sudo systemctl restart medals-deployment
