name: Build and Test Backend

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.event_name != 'workflow_dispatch'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup


  publish-build:
    name: Publish Backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.MEDALS_DOCKER_USERNAME }}
          password: ${{ secrets.MEDALS_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{vars.MEDALS_DOCKER_USERNAME}}/medals-backend

      - name: Push Docker image
        run: docker push ${{vars.MEDALS_DOCKER_USERNAME}}/medals-backend
