name: Detect Secrets

on: push

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets

      - name: Setup baseline detect-secrets
        run: detect-secrets scan
          --exclude-files "docker/README.md"
          --exclude-secrets "toor" --exclude-secrets "password"
          --exclude-secrets "localDataBasePassword"
          --exclude-secrets "2bdff806c775df3d3a9a720924294d3f6dfa4e4e8f65183294bc8b8f043987ac" >
          .secrets.baseline

      - name: Run detect-secrets
        run: detect-secrets audit .secrets.baseline
